### PR TITLE
Add Django 1.11 and Python 3.6/3.7

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by jonashaag** [comment]
Test failures are unrelated to these changes.

**Comment by jheld** [comment]
@jonashaag any update on this?

**Comment by jonashaag** [comment]
The patch is ready and works. Only waiting for the merge

**Comment by kigawas** [comment]
Why not merge?

**Comment by ask** [comment]
Thanks! Merged into master

**Pull request closed without merging**
